package:
  name: mypkg
  version: "0.1.0"

source:
  path: .
build:
  noarch: python

requirements:
  host:
    - python
  run:
    - pytorch
    - torchvision
    - torchaudio
    - pytorch-geometric
    - torch-sparse
    - torch-scatter
    - torch-cluster
    - torch-spline-conv
    - scipy
    - numpy
    - tqdm
    - lmdb
    - pandas
    - networkx